/**
 * ARCHIVO DE CONFIGURACIÓN DE RETOS
 * Para agregar más, solo copia una línea, cámbiale el ID y el texto.
 */

export interface ItemJuego {
    id: number;
    texto: string;
    tipo: 'VERDAD' | 'RETO';
    nivel: 'NIVEL CAGASTÉN' | 'NIVEL RELA' | 'NIVEL ARREBATAO' | 'NIVEL LA VERGA';
}

export const LISTA_JUEGO: ItemJuego[] = [
    // --- VERDADES CAGASTÉN---
    { id: 1, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es el cuento más chimbo que has echao para sacarle el cuerpo a alguien?' },
    { id: 2, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez te han pillao hablando con un(a) ex?' },
    { id: 3, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'Tira la plena: ¿A quién de este grupo no te aguantas ni un minuto?' },
    { id: 4, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo más barro que has hecho por plata?' },
    { id: 5, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu película animada favorita de la infancia?' },
    { id: 6, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo más vergonzoso que has hecho frente a alguien que te gusta?' },
    { id: 7, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es el sueño más raro que has tenido?' },
    { id: 8, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Si pudieras ser un animal por un día, cuál serías?' },
    { id: 9, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué comida odias que a todo el mundo le gusta?' },
    { id: 10, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu placer culposo?' },
    { id: 11, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál era tu apodo más gracioso de niño?' },
    { id: 12, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es el lugar más extraño en el que te has quedado dormido?' },
    { id: 13, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo primero que harías si ganaras la lotería mañana?' },
    { id: 14, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu talento oculto que nadie conoce?' },
    { id: 15, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Quién fue tu primer "crush" de un famoso?' },
    { id: 16, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es la peor compra que has hecho en tu vida?' },
    { id: 17, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo más infantil que sigues haciendo?' },
    { id: 18, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Si pudieras viajar al pasado, a qué año irías?' },
    { id: 19, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu fobia más irracional?' },
    { id: 20, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué canción cantarías en un karaoke sin dudarlo?' },
    { id: 21, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es el mensaje de texto más gracioso que has enviado por error?' },
    { id: 22, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Si solo pudieras comer una cosa el resto de tu vida, qué sería?' },
    { id: 23, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez te reíste en un momento inapropiado?' },
    { id: 24, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué harías si fueras el único humano en la Tierra por un día?' },
    { id: 25, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Prefieres vivir en la playa o en la montaña?' },
    { id: 26, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Si pudieras cambiar tu nombre, cuál elegirías?' },
    { id: 27, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es el mejor cumplido que has recibido?' },
    { id: 28, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez tuviste un amigo imaginario?' },
    { id: 29, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu serie favorita para ver una y otra vez?' },
    { id: 30, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo que más te hace reír?'},
    // --- VERDADES RELA---
    { id: 31, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 27' },
    { id: 32, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 28' },
    { id: 33, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 29' },
    { id: 34, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 30' },
    { id: 35, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 31' },
    { id: 36, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 32' },
    { id: 37, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 33' },
    { id: 38, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 34' },
    { id: 39, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 35' },
    { id: 40, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 36' },
    { id: 41, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 37' },
    { id: 42, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 38' },
    { id: 43, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 39' },
    { id: 44, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 40' },
    { id: 45, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 41' },
    { id: 46, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 42' },
    { id: 47, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 43' },
    { id: 48, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 44' },
    { id: 49, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 45' },
    { id: 50, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 46' },
    { id: 51, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 47' },
    { id: 52, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 48' },
    { id: 53, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 49' },
    { id: 54, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 50' },
    { id: 55, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 51' },
    { id: 56, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 52' },
    { id: 57, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 53' },
    { id: 58, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 54' },
    { id: 59, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 55' },
    { id: 60, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 56' },

    // --- VERDADES ARREBATAO ---
    { id: 61, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Cuál es la fantasía sexual más rara que has tenido?' },
    { id: 62, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Alguna vez has fingido un orgasmo? ¿Con quién y por qué?' },
    { id: 63, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'Sin decir quien: ¿Cuál es la parte del cuerpo que más te excita de otra persona del grupo?' },
    { id: 64, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has tenido sexo en un lugar público? Detalla dónde y cómo.' },
    { id: 65, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Quién de las personas presentes te parece más atractivo sexualmente y por qué?' },
    { id: 66, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Cuál es tu mayor fetiche?' },
    { id: 67, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has visto porno con alguien más en la habitación? ¿Quién era?' },
    { id: 68, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Alguna vez te has masturbado pensando en alguien que está aquí ahora?' },
    { id: 69, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Qué es lo más sucio que le has dicho a alguien por mensaje?' },
    { id: 70, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has tenido un sueño erótico con alguien de este grupo?' },
    { id: 71, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Prefieres dar o recibir sexo oral? ¿Por qué?' },
    { id: 72, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Cuál es la posición sexual que más te gusta y por qué?' },
    { id: 73, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has usado juguetes sexuales?' },
    { id: 74, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Alguna vez has tenido sexo con más de una persona el mismo día?' },
    { id: 75, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Qué es lo más rápido que has llegado al orgasmo?' },
    { id: 76, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has tenido sexo anal?' },
    { id: 77, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has grabado o fotografiado un encuentro sexual? ¿Lo conservas todavía?' },
    { id: 78, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Alguna vez has pagado o te han pagado por sexo?' },
    { id: 79, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Quién de aquí crees que es el mejor en la cama y por qué?' },
    { id: 80, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has tenido un trío? Si no, elige dos personas del grupo con quienes lo harías' },
    { id: 81, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has tenido sexo con alguien mucho mayor o mucho menor que tú? ¿Cuántos años de diferencia?' },
    { id: 82, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Cuál es la mentira más grande que le has dicho a una pareja sobre sexo?' },
    { id: 83, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Alguna vez has sido infiel?' },
    { id: 84, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has tenido sexo por venganza o para superar a alguien?' },
    { id: 85, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has practicado roleplay sexual? ¿Qué personajes?' },
    { id: 86, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Cuál es el lugar más extraño donde te has masturbado?' },
    { id: 87, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Te excita que te vean mientras tienes sexo?' },
    { id: 88, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has tenido sexo con alguien solo porque estaba muy bueno/a aunque no te caía bien?' },
    { id: 89, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Qué es lo más doloroso que has probado en la cama y te gustó?' },
    { id: 90, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Alguna vez has usado comida durante el sexo? ¿Qué y cómo?' },

    // --- VERDADES LA VERGA ---
    { id: 91, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 87' },
    { id: 92, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 88' },
    { id: 93, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 89' },
    { id: 94, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 90' },
    { id: 95, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 91' },
    { id: 96, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 92' },
    { id: 97, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 93' },
    { id: 98, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 94' },
    { id: 99, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 95' },
    { id: 100, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 96' },
    { id: 101, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 97' },
    { id: 102, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 98' },
    { id: 103, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 99' },
    { id: 104, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 100' },
    { id: 105, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 101' },
    { id: 106, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 102' },
    { id: 107, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 103' },
    { id: 108, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 104' },
    { id: 109, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 105' },
    { id: 110, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 106' },
    { id: 111, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 107' },
    { id: 112, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 108' },
    { id: 113, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 109' },
    { id: 114, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 110' },
    { id: 115, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 111' },
    { id: 116, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 112' },
    { id: 117, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 113' },
    { id: 118, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 114' },
    { id: 119, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 115' },
    { id: 120, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 116' },

    // --- RETOS CAGASTÉN---
    { id: 121, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 1' },
    { id: 122, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 2' },
    { id: 123, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 3' },
    { id: 124, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 4' },
    { id: 125, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 5' },
    { id: 126, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 6' },
    { id: 127, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 7' },
    { id: 128, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 8' },
    { id: 129, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 9' },
    { id: 130, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 10' },
    { id: 131, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 11' },
    { id: 132, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 12' },
    { id: 133, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 13' },
    { id: 134, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 14' },
    { id: 135, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 15' },
    { id: 136, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 16' },
    { id: 137, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 17' },
    { id: 138, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 18' },
    { id: 139, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 19' },
    { id: 140, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 20' },
    { id: 141, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 21' },
    { id: 142, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 22' },
    { id: 143, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 23' },
    { id: 144, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 24' },
    { id: 145, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 25' },
    { id: 146, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 26' },
    { id: 147, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 27' },
    { id: 148, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 28' },
    { id: 149, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 29' },
    { id: 150, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'esperalo 30' },

    // --- RETOS RELA---
    { id: 151, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 31' },
    { id: 152, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 32' },
    { id: 153, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 33' },
    { id: 154, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 34' },
    { id: 155, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 35' },
    { id: 156, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 36' },
    { id: 157, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 37' },
    { id: 158, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 38' },
    { id: 159, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 39' },
    { id: 160, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 40' },
    { id: 161, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 41' },
    { id: 162, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 42' },
    { id: 163, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 43' },
    { id: 164, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 44' },
    { id: 165, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 45' },
    { id: 166, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 46' },
    { id: 167, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 47' },
    { id: 168, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 48' },
    { id: 169, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 49' },
    { id: 170, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 50' },
    { id: 180, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 51' },
    { id: 181, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 52' },
    { id: 182, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 53' },
    { id: 183, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 54' },
    { id: 184, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 55' },
    { id: 185, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 56' },
    { id: 186, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 57' },
    { id: 187, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 58' },
    { id: 188, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 59' },
    { id: 189, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 60' },

    // --- RETOS ARREBATAO---
    { id: 190, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 61' },
    { id: 191, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 62' },
    { id: 192, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 63' },
    { id: 193, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 64' },
    { id: 194, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 65' },
    { id: 195, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 66' },
    { id: 196, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 67' },
    { id: 197, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 68' },
    { id: 198, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 69' },
    { id: 199, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 70' },
    { id: 200, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 71' },
    { id: 201, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 72' },
    { id: 202, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 73' },
    { id: 203, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 74' },
    { id: 204, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 75' },
    { id: 205, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 76' },
    { id: 206, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 77' },
    { id: 207, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 78' },
    { id: 208, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 79' },
    { id: 209, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 80' },
    { id: 210, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 81' },
    { id: 211, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 82' },
    { id: 212, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 83' },
    { id: 213, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 84' },
    { id: 214, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 85' },
    { id: 215, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 86' },
    { id: 216, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 87' },
    { id: 217, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 88' },
    { id: 218, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 89' },
    { id: 219, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 90' },

    // --- RETOS LA VERGA---
    { id: 220, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 91' },
    { id: 221, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 92' },
    { id: 222, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 93' },
    { id: 223, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 94' },
    { id: 224, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 95' },
    { id: 225, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 96' },
    { id: 226, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 97' },
    { id: 227, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 98' },
    { id: 228, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 99' },
    { id: 229, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 100' },
    { id: 230, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 101' },
    { id: 231, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 102' },
    { id: 232, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 103' },
    { id: 233, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 104' },
    { id: 234, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 105' },
    { id: 235, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 106' },
    { id: 236, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 107' },
    { id: 237, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 108' },
    { id: 238, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 109' },
    { id: 239, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 110' },
    { id: 240, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 111' },
    { id: 241, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 112' },
    { id: 242, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 113' },
    { id: 243, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 114' },
    { id: 244, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 115' },
    { id: 245, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 116' },
    { id: 246, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 117' },
    { id: 247, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 118' },
    { id: 248, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 119' },
    { id: 249, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 120' },
];

// Agrega esto al final de tu archivo Retos.ts
export const NIVELES_DISPONIBLES: NivelPicante[] = ['NIVEL CAGASTÉN', 'NIVEL RELA', 'NIVEL ARREBATAO', 'NIVEL LA VERGA'];