/**
 * ARCHIVO DE CONFIGURACIÓN DE RETOS
 * Para agregar más, solo copia una línea, cámbiale el ID y el texto.
 */

export interface ItemJuego {
    id: number;
    texto: string;
    tipo: 'VERDAD' | 'RETO';
    nivel: 'NIVEL CAGASTÉN' | 'NIVEL RELA' | 'NIVEL ARREBATAO' | 'NIVEL LA VERGA';
}

export const LISTA_JUEGO: ItemJuego[] = [
    // --- VERDADES CAGASTÉN---
    { id: 1, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es el cuento más chimbo que has echao para sacarle el cuerpo a alguien?' },
    { id: 2, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez te han pillao hablando con un(a) ex?' },
    { id: 3, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'Tira la plena: ¿A quién de este grupo no te aguantas ni un minuto?' },
    { id: 4, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo más barro que has hecho por plata?' },
    { id: 5, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 1' },
    { id: 6, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 2' },
    { id: 7, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 3' },
    { id: 8, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 4' },
    { id: 9, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 5' },
    { id: 10, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 6' },
    { id: 11, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 7' },
    { id: 12, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 8' },
    { id: 13, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 9' },
    { id: 14, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 10' },
    { id: 15, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 11' },
    { id: 16, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 12' },
    { id: 17, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 13' },
    { id: 18, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 14' },
    { id: 19, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 15' },
    { id: 20, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 16' },
    { id: 21, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 17' },
    { id: 22, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 18' },
    { id: 23, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 19' },
    { id: 24, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 20' },
    { id: 25, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 21' },
    { id: 26, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 22' },
    { id: 27, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 23' },
    { id: 28, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 24' },
    { id: 29, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 25' },
    { id: 30, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'esperala 26'},
    // --- VERDADES RELA---
    { id: 31, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 27' },
    { id: 32, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 28' },
    { id: 33, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 29' },
    { id: 34, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 30' },
    { id: 35, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 31' },
    { id: 36, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 32' },
    { id: 37, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 33' },
    { id: 38, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 34' },
    { id: 39, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 35' },
    { id: 40, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 36' },
    { id: 41, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 37' },
    { id: 42, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 38' },
    { id: 43, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 39' },
    { id: 44, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 40' },
    { id: 45, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 41' },
    { id: 46, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 42' },
    { id: 47, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 43' },
    { id: 48, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 44' },
    { id: 49, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 45' },
    { id: 50, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 46' },
    { id: 51, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 47' },
    { id: 52, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 48' },
    { id: 53, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 49' },
    { id: 54, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 50' },
    { id: 55, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 51' },
    { id: 56, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 52' },
    { id: 57, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 53' },
    { id: 58, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 54' },
    { id: 59, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 55' },
    { id: 60, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 56' },

    // --- VERDADES ARREBATAO ---
    { id: 1, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 57' },
    { id: 2, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 58' },
    { id: 3, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 59' },
    { id: 4, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 60' },
    { id: 5, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 61' },
    { id: 6, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 62' },
    { id: 7, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 63' },
    { id: 8, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 64' },
    { id: 9, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 65' },
    { id: 10, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 66' },
    { id: 11, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 67' },
    { id: 12, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 68' },
    { id: 13, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 69' },
    { id: 14, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 70' },
    { id: 15, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 71' },
    { id: 16, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 72' },
    { id: 17, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 73' },
    { id: 18, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 74' },
    { id: 19, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 75' },
    { id: 20, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 76' },
    { id: 21, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 77' },
    { id: 22, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 78' },
    { id: 23, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 79' },
    { id: 24, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 80' },
    { id: 25, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 81' },
    { id: 26, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 82' },
    { id: 27, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 83' },
    { id: 28, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 84' },
    { id: 29, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 85' },
    { id: 30, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'esperala 86' },

    // --- VERDADES LA VERGA ---
    { id: 1, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 87' },
    { id: 2, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 88' },
    { id: 3, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 89' },
    { id: 4, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 90' },
    { id: 5, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 91' },
    { id: 6, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 92' },
    { id: 7, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 93' },
    { id: 8, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 94' },
    { id: 9, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 95' },
    { id: 10, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 96' },
    { id: 11, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 97' },
    { id: 12, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 98' },
    { id: 13, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 99' },
    { id: 14, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 100' },
    { id: 15, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 101' },
    { id: 16, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 102' },
    { id: 17, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 103' },
    { id: 18, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 104' },
    { id: 19, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 105' },
    { id: 20, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 106' },
    { id: 21, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 107' },
    { id: 22, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 108' },
    { id: 23, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 109' },
    { id: 24, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 110' },
    { id: 25, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 111' },
    { id: 26, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 112' },
    { id: 27, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 113' },
    { id: 28, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 114' },
    { id: 29, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 115' },
    { id: 30, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 116' },

    // --- RETOS ---
    { id: 6, tipo: 'RETO', nivel: 'SUAVE', texto: 'Párate y baila un pase de champeta "el caballito" por 10 segundos.' },
    { id: 7, tipo: 'RETO', nivel: 'PUYUO', texto: 'Llama a un contacto y dile: "Ajá y qué, ¿te vas a quedar en esa?" y cuelga.' },
    { id: 8, tipo: 'RETO', nivel: 'ARREBATAO', texto: 'Déjate revisar el WhatsApp por la persona que tienes a la derecha.' },
    { id: 9, tipo: 'RETO', nivel: 'SUAVE', texto: 'Pidele prestado un poquito de sal al vecino con voz de borracho.' },
];