/**
 * ARCHIVO DE CONFIGURACIÓN DE RETOS
 * Para agregar más, solo copia una línea, cámbiale el ID y el texto.
 */

export interface ItemJuego {
    id: number;
    texto: string;
    tipo: 'VERDAD' | 'RETO';
    nivel: 'NIVEL CAGASTÉN' | 'NIVEL RELA' | 'NIVEL ARREBATAO' | 'NIVEL LA VERGA';
}

export const LISTA_JUEGO: ItemJuego[] = [
    // --- VERDADES CAGASTÉN---
    { id: 1, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es el cuento más chimbo que has echao para sacarle el cuerpo a alguien?' },
    { id: 2, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez te han pillao hablando con un(a) ex?' },
    { id: 3, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: 'Tira la plena: ¿A quién de este grupo no te aguantas ni un minuto?' },
    { id: 4, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo más barro que has hecho por plata?' },
    { id: 5, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu película animada favorita de la infancia?' },
    { id: 6, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo más vergonzoso que has hecho frente a alguien que te gusta?' },
    { id: 7, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es el sueño más raro que has tenido?' },
    { id: 8, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Si pudieras ser un animal por un día, cuál serías?' },
    { id: 9, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué comida odias que a todo el mundo le gusta?' },
    { id: 10, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu placer culposo?' },
    { id: 11, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál era tu apodo más gracioso de niño?' },
    { id: 12, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es el lugar más extraño en el que te has quedado dormido?' },
    { id: 13, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo primero que harías si ganaras la lotería mañana?' },
    { id: 14, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu talento oculto que nadie conoce?' },
    { id: 15, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Quién fue tu primer "crush" de un famoso?' },
    { id: 16, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es la peor compra que has hecho en tu vida?' },
    { id: 17, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo más infantil que sigues haciendo?' },
    { id: 18, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Si pudieras viajar al pasado, a qué año irías?' },
    { id: 19, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu fobia más irracional?' },
    { id: 20, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué canción cantarías en un karaoke sin dudarlo?' },
    { id: 21, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es el mensaje de texto más gracioso que has enviado por error?' },
    { id: 22, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Si solo pudieras comer una cosa el resto de tu vida, qué sería?' },
    { id: 23, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez te reíste en un momento inapropiado?' },
    { id: 24, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué harías si fueras el único humano en la Tierra por un día?' },
    { id: 25, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Prefieres vivir en la playa o en la montaña?' },
    { id: 26, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Si pudieras cambiar tu nombre, cuál elegirías?' },
    { id: 27, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es el mejor cumplido que has recibido?' },
    { id: 28, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez tuviste un amigo imaginario?' },
    { id: 29, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu serie favorita para ver una y otra vez?' },
    { id: 30, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo que más te hace reír?' },
    // Nuevas Verdades Cagastén (31-130)
    { id: 31, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿A qué edad perdiste la virginidad?' },
    { id: 32, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es el rumor más falso que han dicho sobre ti?' },
    { id: 33, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Quién de este grupo te cae peor?' },
    { id: 34, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has revisado el celular de tu pareja sin permiso?' },
    { id: 35, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo más asqueroso que has comido?' },
    { id: 36, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez te has orinado en público siendo adulto?' },
    { id: 37, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Quién fue tu peor beso?' },
    { id: 38, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez te han arrestado o detenido?' },
    { id: 39, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué harías si fueras invisible por un día?' },
    { id: 40, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu peor hábito?' },
    { id: 41, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has estado enamorado de alguien de este grupo?' },
    { id: 42, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Te has acostado con alguien en la primera cita?' },
    { id: 43, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo más ilegal que has hecho?' },
    { id: 44, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has robado algo?' },
    { id: 45, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu mayor inseguridad?' },
    { id: 46, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has mandado nudes alguna vez?' },
    { id: 47, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Quién es la persona más sexy de este grupo?' },
    { id: 48, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez te ha gustado la pareja de un amigo?' },
    { id: 49, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es la mentira más grande que has dicho para no ir a un lugar?' },
    { id: 50, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has tenido sexo en la casa de tus padres?' },
    { id: 51, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué parte de tu cuerpo te gusta menos?' },
    { id: 52, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has dudado de tu orientación sexual?' },
    { id: 53, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Quién es la persona que más te ha hecho llorar?' },
    { id: 54, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has tenido una ETS?' },
    { id: 55, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu mayor arrepentimiento amoroso?' },
    { id: 56, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Te han sido infiel alguna vez?' },
    { id: 57, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo peor que le has hecho a un amigo?' },
    { id: 58, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has besado a más de una persona en una noche?' },
    { id: 59, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez te has enamorado de un profesor?' },
    { id: 60, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué opinas del poliamor?' },
    { id: 61, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es la cita más desastrosa que has tenido?' },
    { id: 62, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has tenido sexo virtual?' },
    { id: 63, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez te has vomitado encima de alguien?' },
    { id: 64, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo más vergonzoso que te ha pasado en la cama?' },
    { id: 65, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has usado Tinder u otra app de citas?' },
    { id: 66, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has stalkeado a alguien obsesivamente?' },
    { id: 67, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo que más te molesta de tu mejor amigo?' },
    { id: 68, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has tenido sexo con alguien solo por despecho?' },
    { id: 69, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has fingido estar enfermo para no trabajar?' },
    { id: 70, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es el secreto más oscuro que guardas?' },
    { id: 71, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has tenido un "amigo con derechos"?' },
    { id: 72, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez te has enamorado por internet?' },
    { id: 73, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué harías si descubrieras que te queda un año de vida?' },
    { id: 74, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has tenido una experiencia paranormal?' },
    { id: 75, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has deseado la muerte de alguien?' },
    { id: 76, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo más caro que has roto y no lo dijiste?' },
    { id: 77, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Te has besado con alguien del mismo sexo?' },
    { id: 78, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu peor defecto?' },
    { id: 79, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has espiado a tus vecinos?' },
    { id: 80, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo más raro que has comido?' },
    { id: 81, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has tenido sexo en un coche?' },
    { id: 82, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has llorado durante el sexo?' },
    { id: 83, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Quién es tu "amor platónico"?' },
    { id: 84, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Te has operado algo o te gustaría hacerlo?' },
    { id: 85, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo que más te avergüenza de tu familia?' },
    { id: 86, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has sido el "otro" o la "otra"?' },
    { id: 87, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has tenido sexo sin protección con un desconocido?' },
    { id: 88, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo más loco que has hecho por amor?' },
    { id: 89, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has traicionado a un amigo?' },
    { id: 90, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Te has acostado con alguien por interés?' },
    { id: 91, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu mayor miedo?' },
    { id: 92, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has tenido sexo con alguien de tu trabajo?' },
    { id: 93, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has grabado a alguien sin su consentimiento?' },
    { id: 94, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué harías si fueras del sexo opuesto por un día?' },
    { id: 95, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has mentido sobre tu edad?' },
    { id: 96, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es el chisme más grande que sabes de alguien aquí?' },
    { id: 97, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Te has arrepentido de acostarte con alguien?' },
    { id: 98, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has fingido que te gustaba un regalo?' },
    { id: 99, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo más feo que te han dicho?' },
    { id: 100, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has tenido sexo en la playa?' },
    { id: 101, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez te has sentido atraído por un familiar lejano?' },
    { id: 102, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es la situación más incómoda que has vivido?' },
    { id: 103, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has tenido sexo con alguien cuyo nombre no recuerdas?' },
    { id: 104, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo que más te excita?' },
    { id: 105, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has sido arrestado?' },
    { id: 106, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Te has besado con alguien comprometido?' },
    { id: 107, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo peor que has hecho estando borracho?' },
    { id: 108, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has tenido sexo en un baño público?' },
    { id: 109, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has dudado de ser el padre/madre de tus hijos (hipotéticamente)?' },
    { id: 110, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu posición sexual favorita?' },
    { id: 111, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has tenido sexo anal?' },
    { id: 112, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has hecho un trío?' },
    { id: 113, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Te gustaría hacer un intercambio de parejas?' },
    { id: 114, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has mirado porno hoy?' },
    { id: 115, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu categoría de porno favorita?' },
    { id: 116, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez te has masturbado en el trabajo?' },
    { id: 117, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has tenido sexo telefónico?' },
    { id: 118, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Te has grabado teniendo sexo?' },
    { id: 119, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has pagado por sexo?' },
    { id: 120, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Te has acostado con la expareja de un amigo?' },
    { id: 121, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has tenido sexo con alguien mucho mayor que tú?' },
    { id: 122, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has fingido estar dormido para no tener sexo?' },
    { id: 123, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Qué es lo más extraño que te excita?' },
    { id: 124, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has tenido sexo en una piscina?' },
    { id: 125, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez te han pillado teniendo sexo?' },
    { id: 126, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Te has acostado con alguien solo porque tenía dinero?' },
    { id: 127, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Cuál es tu juguete sexual favorito?' },
    { id: 128, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Has tenido sexo BDSM?' },
    { id: 129, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Alguna vez has tenido una fantasía con un personaje de dibujos animados?' },
    { id: 130, tipo: 'VERDAD', nivel: 'NIVEL CAGASTÉN', texto: '¿Te has acostado con alguien y luego te has olvidado de su nombre?' },

    // --- VERDADES RELA (Renumbered starts at 131) --- 
    { id: 131, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 27' },
    { id: 132, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 28' },
    { id: 133, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 29' },
    { id: 134, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 30' },
    { id: 135, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 31' },
    { id: 136, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 32' },
    { id: 137, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 33' },
    { id: 138, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 34' },
    { id: 139, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 35' },
    { id: 140, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 36' },
    { id: 141, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 37' },
    { id: 142, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 38' },
    { id: 143, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 39' },
    { id: 144, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 40' },
    { id: 145, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 41' },
    { id: 146, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 42' },
    { id: 147, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 43' },
    { id: 148, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 44' },
    { id: 149, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 45' },
    { id: 150, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 46' },
    { id: 151, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 47' },
    { id: 152, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 48' },
    { id: 153, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 49' },
    { id: 154, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 50' },
    { id: 155, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 51' },
    { id: 156, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 52' },
    { id: 157, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 53' },
    { id: 158, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 54' },
    { id: 159, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 55' },
    { id: 160, tipo: 'VERDAD', nivel: 'NIVEL RELA', texto: 'esperala 56' },


    // --- VERDADES ARREBATAO (Renumbered starts at 161) ---
    { id: 161, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Cuál es la fantasía sexual más rara que has tenido?' },
    { id: 162, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Alguna vez has fingido un orgasmo? ¿Con quién y por qué?' },
    { id: 163, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: 'Sin decir quien: ¿Cuál es la parte del cuerpo que más te excita de otra persona del grupo?' },
    { id: 164, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has tenido sexo en un lugar público? Detalla dónde y cómo.' },
    { id: 165, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Quién de las personas presentes te parece más atractivo sexualmente y por qué?' },
    { id: 166, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Cuál es tu mayor fetiche?' },
    { id: 167, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has visto porno con alguien más en la habitación? ¿Quién era?' },
    { id: 168, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Alguna vez te has masturbado pensando en alguien que está aquí ahora?' },
    { id: 169, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Qué es lo más sucio que le has dicho a alguien por mensaje?' },
    { id: 170, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has tenido un sueño erótico con alguien de este grupo?' },
    { id: 171, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Prefieres dar o recibir sexo oral? ¿Por qué?' },
    { id: 172, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Cuál es la posición sexual que más te gusta y por qué?' },
    { id: 173, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has usado juguetes sexuales?' },
    { id: 174, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Alguna vez has tenido sexo con más de una persona el mismo día?' },
    { id: 175, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Qué es lo más rápido que has llegado al orgasmo?' },
    { id: 176, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has tenido sexo anal?' },
    { id: 177, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has grabado o fotografiado un encuentro sexual? ¿Lo conservas todavía?' },
    { id: 178, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Alguna vez has pagado o te han pagado por sexo?' },
    { id: 179, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Quién de aquí crees que es el mejor en la cama y por qué?' },
    { id: 180, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has tenido un trío? Si no, elige dos personas del grupo con quienes lo harías' },
    { id: 181, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has tenido sexo con alguien mucho mayor o mucho menor que tú? ¿Cuántos años de diferencia?' },
    { id: 182, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Cuál es la mentira más grande que le has dicho a una pareja sobre sexo?' },
    { id: 183, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Alguna vez has sido infiel?' },
    { id: 184, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has tenido sexo por venganza o para superar a alguien?' },
    { id: 185, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has practicado roleplay sexual? ¿Qué personajes?' },
    { id: 186, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Cuál es el lugar más extraño donde te has masturbado?' },
    { id: 187, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Te excita que te vean mientras tienes sexo?' },
    { id: 188, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Has tenido sexo con alguien solo porque estaba muy bueno/a aunque no te caía bien?' },
    { id: 189, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Qué es lo más doloroso que has probado en la cama y te gustó?' },
    { id: 190, tipo: 'VERDAD', nivel: 'NIVEL ARREBATAO', texto: '¿Alguna vez has usado comida durante el sexo? ¿Qué y cómo?' },

    // --- VERDADES LA VERGA (Renumbered starts at 191) ---
    { id: 191, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 87' },
    { id: 192, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 88' },
    { id: 193, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 89' },
    { id: 194, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 90' },
    { id: 195, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 91' },
    { id: 196, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 92' },
    { id: 197, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 93' },
    { id: 198, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 94' },
    { id: 199, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 95' },
    { id: 200, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 96' },
    { id: 201, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 97' },
    { id: 202, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 98' },
    { id: 203, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 99' },
    { id: 204, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 100' },
    { id: 205, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 101' },
    { id: 206, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 102' },
    { id: 207, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 103' },
    { id: 208, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 104' },
    { id: 209, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 105' },
    { id: 210, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 106' },
    { id: 211, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 107' },
    { id: 212, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 108' },
    { id: 213, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 109' },
    { id: 214, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 110' },
    { id: 215, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 111' },
    { id: 216, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 112' },
    { id: 217, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 113' },
    { id: 218, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 114' },
    { id: 219, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 115' },
    { id: 220, tipo: 'VERDAD', nivel: 'NIVEL LA VERGA', texto: 'esperala 116' },

    // --- RETOS CAGASTÉN (Renumbered starts at 221) ---
    { id: 221, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Deja que el grupo envíe un mensaje a tu última conversación de WhatsApp con lo que ellos quieran.' },
    { id: 222, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Llama a tu ex y dile que todavía lo/la extrañas (o a tu crush si no tienes ex).' },
    { id: 223, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Sal a la calle (o al balcón) y grita "¡TENGO DIARREA!" lo más fuerte posible.' },
    { id: 224, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Publica una historia en Instagram/Facebook declarándole tu amor a un objeto inanimado.' },
    { id: 225, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Muestra tu historial de búsqueda de Google al grupo.' },
    { id: 226, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Deja que el grupo te prepare un shot con los ingredientes que encuentren y bébetelo (sin veneno, obvio).' },
    { id: 227, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Envía un audio gimiendo al tercer contacto activo de tu WhatsApp.' },
    { id: 228, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Baila sensualmente sin música frente a todos por 1 minuto.' },
    { id: 229, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Intercambia una prenda de ropa con la persona a tu derecha.' },
    { id: 230, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Deja que el grupo revise tu galería de fotos por 1 minuto completo.' },
    { id: 231, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Llama a tu mamá/papá y diles que te vas a casar en secreto mañana.' },
    { id: 232, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Huele las axilas de la persona a tu izquierda y describe el olor.' },
    { id: 233, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Ponte "En una relación" con alguien del grupo en redes sociales por 24 horas.' },
    { id: 234, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Deja que alguien del grupo te escriba una palabra en la frente con marcador (borrable o no, deciden ellos).' },
    { id: 235, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Hazte pasar por un perro y ládrale a todos por 2 minutos.' },
    { id: 236, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Manda una foto de tus pies a la persona que el grupo elija de tus contactos.' },
    { id: 237, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Lee en voz alta los últimos 5 mensajes de tu chat fijado.' },
    { id: 238, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Haz 20 sentadillas con alguien del grupo cargado en tu espalda.' },
    { id: 239, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Deja que el grupo te maquille o te peine como ellos quieran y quédate así el resto del juego.' },
    { id: 240, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Camina como cangrejo por toda la habitación durante un turno.' },
    { id: 241, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Muerde suavemente la oreja de la persona a tu izquierda.' },
    { id: 242, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Quítate dos prendas de ropa (los zapatos no cuentan).' },
    { id: 243, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Llama a un número al azar y canta el "Feliz Cumpleaños" a quien conteste.' },
    { id: 244, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Habla con acento de telenovela mexicana por las próximas 3 rondas.' },
    { id: 245, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Bebe un vaso de agua (o lo que estés tomando) sin usar las manos.' },
    { id: 246, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Dibuja un bigote o un pene en tu cara y déjalo ahí por el resto del juego.' },
    { id: 247, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Deja que alguien te depile una pequeña parte de la pierna o brazo con cinta adhesiva.' },
    { id: 248, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Lame el cuello de la persona que tienes enfrente.' },
    { id: 249, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Haz un baile de TikTok (el que el grupo elija) y súbelo a tus historias.' },
    { id: 250, tipo: 'RETO', nivel: 'NIVEL CAGASTÉN', texto: 'Quédate en ropa interior por 2 rondas (o quítate la camisa si ya estás en confianza).' },

    // --- RETOS RELA (Renumbered starts at 251)---
    { id: 251, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'Tragate un huevo crudo' },
    { id: 252, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 32' },
    { id: 253, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 33' },
    { id: 254, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 34' },
    { id: 255, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 35' },
    { id: 256, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 36' },
    { id: 257, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 37' },
    { id: 258, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 38' },
    { id: 259, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 39' },
    { id: 260, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 40' },
    { id: 261, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 41' },
    { id: 262, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 42' },
    { id: 263, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 43' },
    { id: 264, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 44' },
    { id: 265, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 45' },
    { id: 266, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 46' },
    { id: 267, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 47' },
    { id: 268, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 48' },
    { id: 269, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 49' },
    { id: 270, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 50' },
    { id: 280, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 51' },
    { id: 281, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 52' },
    { id: 282, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 53' },
    { id: 283, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 54' },
    { id: 284, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 55' },
    { id: 285, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 56' },
    { id: 286, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 57' },
    { id: 287, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 58' },
    { id: 288, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 59' },
    { id: 289, tipo: 'RETO', nivel: 'NIVEL RELA', texto: 'esperalo 60' },

    // --- RETOS ARREBATAO (Renumbered starts at 290)---
    { id: 290, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'Que el grupo elija alguien para que le des un beso en la nalga' },
    { id: 291, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 62' },
    { id: 292, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 63' },
    { id: 293, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 64' },
    { id: 294, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 65' },
    { id: 295, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 66' },
    { id: 296, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 67' },
    { id: 297, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 68' },
    { id: 298, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 69' },
    { id: 299, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 70' },
    { id: 300, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 71' },
    { id: 301, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 72' },
    { id: 302, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 73' },
    { id: 303, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 74' },
    { id: 304, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 75' },
    { id: 305, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 76' },
    { id: 306, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 77' },
    { id: 307, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 78' },
    { id: 308, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 79' },
    { id: 309, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 80' },
    { id: 310, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 81' },
    { id: 311, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 82' },
    { id: 312, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 83' },
    { id: 313, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 84' },
    { id: 314, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 85' },
    { id: 315, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 86' },
    { id: 316, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 87' },
    { id: 317, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 88' },
    { id: 318, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 89' },
    { id: 319, tipo: 'RETO', nivel: 'NIVEL ARREBATAO', texto: 'esperalo 90' },

    // --- RETOS LA VERGA (Renumbered starts at 320)---
    { id: 320, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 91' },
    { id: 321, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 92' },
    { id: 322, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 93' },
    { id: 323, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 94' },
    { id: 324, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 95' },
    { id: 325, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 96' },
    { id: 326, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 97' },
    { id: 327, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 98' },
    { id: 328, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 99' },
    { id: 329, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 100' },
    { id: 330, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 101' },
    { id: 331, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 102' },
    { id: 332, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 103' },
    { id: 333, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 104' },
    { id: 334, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 105' },
    { id: 335, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 106' },
    { id: 336, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 107' },
    { id: 337, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 108' },
    { id: 338, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 109' },
    { id: 339, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 110' },
    { id: 340, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 111' },
    { id: 341, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 112' },
    { id: 342, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 113' },
    { id: 343, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 114' },
    { id: 344, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 115' },
    { id: 345, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 116' },
    { id: 346, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 117' },
    { id: 347, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 118' },
    { id: 348, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 119' },
    { id: 349, tipo: 'RETO', nivel: 'NIVEL LA VERGA', texto: 'esperalo 120' },
];

// Agrega esto al final de tu archivo Retos.ts
export const NIVELES_DISPONIBLES: NivelPicante[] = ['NIVEL CAGASTÉN', 'NIVEL RELA', 'NIVEL ARREBATAO', 'NIVEL LA VERGA'];